#!/usr/bin/env python3
"""
Auto-generate litellm_config.yaml from currently available AWS profiles.

Only includes profiles that exist in ~/.aws/credentials, so dead/expired
profiles won't cause 500 errors.

Usage:
    python scripts/gen_litellm_config.py
    python scripts/gen_litellm_config.py --output litellm_config.yaml
"""

import argparse
import os
import re
import yaml


MODELS = [
    # {
    #     "name": "gpt-4.1-mini",
    #     "bedrock_model": "bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0",
    #     "id_suffix": "sonnet-4",
    # },
    {
        "name": "sonnet-4",
        "bedrock_model": "bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0",
        "id_suffix": "sonnet-4",
    },
    # {
    #     "name": "haiku-3",
    #     "bedrock_model": "bedrock/anthropic.claude-3-haiku-20240307-v1:0",
    #     "id_suffix": "haiku-3",
    # },
    # {
    #     "name": "opus-4-6",
    #     "bedrock_model": "bedrock/us.anthropic.claude-opus-4-6-v1",
    #     "id_suffix": "opus-46",
    #     "max_profiles": 6,
    # },
]

REGION = "us-east-1"


def get_available_profiles():
    """Read profile names from ~/.aws/credentials."""
    creds_path = os.path.expanduser("~/.aws/credentials")
    if not os.path.exists(creds_path):
        return []
    with open(creds_path) as f:
        return re.findall(r"^\[(.+?)\]", f.read(), re.MULTILINE)


def generate_config(profiles):
    model_list = []

    for model_def in MODELS:
        max_p = model_def.get("max_profiles", len(profiles))
        for i, profile in enumerate(profiles):
            if i >= max_p:
                break
            model_list.append({
                "model_name": model_def["name"],
                "litellm_params": {
                    "model": model_def["bedrock_model"],
                    "aws_profile_name": profile,
                    "aws_region_name": REGION,
                },
                "model_info": {
                    "id": f"{profile}-{model_def['id_suffix']}",
                },
            })

    config = {
        "model_list": model_list,
        "router_settings": {
            "routing_strategy": "least-busy",
            "num_retries": 5,
            "timeout": 300,
            "retry_after": 2,
            "allowed_fails": 1,
            "cooldown_time": 300,
        },
        "general_settings": {
            "drop_params": True,
        },
    }
    return config


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", default="litellm_config.yaml")
    args = parser.parse_args()

    profiles = get_available_profiles()
    print(f"Found {len(profiles)} AWS profiles in ~/.aws/credentials")

    if not profiles:
        print("ERROR: No profiles found. Run source_all_bedrock_accounts.sh first.")
        return

    config = generate_config(profiles)

    total = len(config["model_list"])
    models = set(m["model_name"] for m in config["model_list"])
    print(f"Generated {total} endpoints across models: {models}")

    with open(args.output, "w") as f:
        f.write("# Auto-generated by gen_litellm_config.py\n")
        f.write(f"# {len(profiles)} AWS profiles, {total} endpoints\n\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    print(f"Written to {args.output}")


if __name__ == "__main__":
    main()
